remote_theme: pages-themes/midnight@v0.2.0

title: "Assignment"
description: "Rendering Mermaid Js Code"

show_downloads: true

mermaid:
  enabled: true

github:
  zip_url: http://mantejjosan.com/assignment1
