remote_theme: pages-themes/midnight@v0.2.0

title: Assignment-1
description: PPS subject C++ Topic
show_downloads: true

mermaid:
  enabled: true

github:
  zip_url: http://mantejjosan.com/assignment1
