remote_theme: pages-themes/midnight@v0.2.0

title: mantejjosan
description: Programming for Problem Solving
show_downloads: true

mermaid:
  enabled: true

github:
  zip_url: http://mantejjosan.com/assignment1
